### ISSUE TITLE
Bug in new app available toast notification

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#5938] opened 2023-09-23 14:01 UTC
I saw this bug in the new app available toast notification today.

![toast](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/bec396d0-8802-47f2-b2cd-3b315755ad3c)

Link seems to be escaped...

**Comment by phiphou** [comment] 2023-09-27 16:11
Same thing today...

![toast2](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/1d3da279-b4bd-4504-b676-df38f76df995)

**Comment by VIKTORVAV99** [comment] 2023-09-30 08:25
I can't seem to replicate this in the app so I'll dig through the code later today and see if I can find the cause.

**Comment by phiphou** [comment] 2023-09-30 10:12
The problem is in `web/src/components/Toast.tsx`.

Title is escape by default.

We could use something like this : 

```js
import * as DOMPurify from 'dompurify';

const cleanTitle = DOMPurify.sanitize(__('misc.newversion'));
```

and 

```js
<Toast
  title={cleanTitle }
  toastAction={handleReload}
  isCloseable={true}
  toastActionText={__('misc.reload')}
/>
```

**Comment by VIKTORVAV99** [comment] 2023-09-30 10:47
I don't even think there should be a link in the text anymore though, so it might just be the translation files.

**Comment by phiphou** [comment] 2023-09-30 13:04
Seems legit, while there is the toastAction property.

**Comment by phiphou** [comment] 2023-10-12 16:38
Still the same bug today...

![9879878](https://github.com/electricitymaps/electricitymaps-contrib/assets/364418/48318400-a689-4b80-8d6d-c0b9f2195422)

**Comment by madsnedergaard** [comment] 2023-10-15 21:53
It is happening after https://github.com/electricitymaps/electricitymaps-contrib/pull/5801 was merged, which basically switched from a hardcoded string back to the old translations. We should go through all translation files and update the text to fix this :)

**Comment by phiphou** [comment] 2023-10-20 16:40
Forgot to mention that the choices buttons (reload and dismiss) are not translated.

**Comment by charwebb** [comment] 2023-11-13 03:02
Reload and dismiss are not translated because #5801 switched to using misc.reload and misc.dismiss which they also only set in English. I am going to patch this issue right now.

**Closed** 2023-11-30 19:52 UTC
Labels: bug 🐞, help wanted, frontend 🎨
