### ISSUE TITLE
[Data Issue]: Super low carbon intensity for Sweden in yearly aggregation for no apparent reason (2g co2eq/kWh)

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#4740] opened 2022-11-02 23:25 UTC
### When did this happen?

2021

### What zones are affected?

SE

### What is the problem?

The carbon intensity for Sweden is super low in yearly aggregation for 2021 and the past data for 2017-2020 is gone.
![image](https://user-images.githubusercontent.com/30777521/199620699-a0deda8f-9692-4cc5-9018-62323a224f1f.png)
![image](https://user-images.githubusercontent.com/30777521/199620754-3d694589-b024-40c6-8613-16fa9be9722d.png)
Yearly state file:
```json
{
    "data": {
        "hasData": true,
        "stateAggregation": "yearly",
        "zoneStates": [
            {
                "_isFinestGranularity": false,
                "co2intensity": 41.92,
                "co2intensityProduction": 37.52,
                "countryCode": "SE",
                "dischargeCo2Intensities": {
                    "battery": 42.64305535137137,
                    "hydro": 42.64305535137137
                },
                "dischargeCo2IntensitySources": {
                    "battery": "electricityMap, 2017 average",
                    "hydro": "electricityMap, 2017 average"
                },
                "exchange": {},
                "fossilFuelRatio": 0.015300000000000001,
                "fossilFuelRatioProduction": 0.0091,
                "isValid": true,
                "maxDischarge": 0,
                "maxExport": 0,
                "maxImport": 0,
                "maxProduction": 7456.26,
                "maxStorage": 0,
                "maxStorageCapacity": 0,
                "price": {
                    "currency": null,
                    "value": null
                },
                "production": {
                    "biomass": 0.0,
                    "coal": 0.0,
                    "gas": 0.0,
                    "geothermal": 0.0,
                    "hydro": 7456.26,
                    "nuclear": 7192.43,
                    "oil": 0.0,
                    "solar": 0.0,
                    "unknown": 1443.55,
                    "wind": 1963.04
                },
                "productionCo2Intensities": {
                    "biomass": 230,
                    "coal": 820,
                    "gas": 490,
                    "geothermal": 38,
                    "hydro": 24,
                    "nuclear": 12,
                    "oil": 650,
                    "solar": 45,
                    "unknown": 270.6,
                    "wind": 11
                },
                "productionCo2IntensitySources": {
                    "biomass": "IPCC 2014",
                    "coal": "IPCC 2014",
                    "gas": "IPCC 2014",
                    "geothermal": "IPCC 2014",
                    "hydro": "IPCC 2014",
                    "nuclear": "IPCC 2014",
                    "oil": "UK POST 2014",
                    "solar": "IPCC 2014",
                    "unknown": "assumes 87.2% biomass, 6.21% gas, 2.04% coal, 1.84% oil, 1.46% solar, 1.26% peat",
                    "wind": "IPCC 2014"
                },
                "renewableRatio": 0.6108,
                "renewableRatioProduction": 0.5926,
                "source": "\"electricityMap Estimation\",\"svk.se\",\"svk.se\"",
                "stateDatetime": "2017-01-01T00:00:00Z",
                "storage": {
                    "battery": null,
                    "hydro": null
                },
                "totalCo2Discharge": 0,
                "totalCo2Export": 0,
                "totalCo2Import": 0,
                "totalCo2NetExchange": 0,
                "totalCo2Production": 677477470.0,
                "totalCo2Storage": 0,
                "totalConsumption": 15563.11,
                "totalDischarge": null,
                "totalExport": 3706.2,
                "totalImport": 1214.04,
                "totalProduction": 18055.28,
                "totalStorage": null
            },
            {
                "isValid": false,
                "stateDatetime": "2018-01-01T00:00:00Z"
            },
            {
                "isValid": false,
                "stateDatetime": "2019-01-01T00:00:00Z"
            },
            {
                "isValid": false,
                "stateDatetime": "2020-01-01T00:00:00Z"
            },
            {
                "_isFinestGranularity": false,
                "co2intensity": 1.84,
                "co2intensityProduction": 34.64,
                "countryCode": "SE",
                "dischargeCo2Intensities": {
                    "battery": 42.07081808517848,
                    "hydro": 42.07081808517848
                },
                "dischargeCo2IntensitySources": {
                    "battery": "electricityMap, 2021 average",
                    "hydro": "electricityMap, 2021 average"
                },
                "exchange": {},
                "fossilFuelRatio": 0.0006,
                "fossilFuelRatioProduction": 0.0052,
                "isValid": true,
                "maxDischarge": 0,
                "maxExport": 0,
                "maxImport": 0,
                "maxProduction": 8501.84,
                "maxStorage": 0,
                "maxStorageCapacity": 0,
                "price": {
                    "currency": null,
                    "value": null
                },
                "production": {
                    "biomass": 0.0,
                    "coal": 0.0,
                    "gas": 0.36,
                    "geothermal": 0.0,
                    "hydro": 8501.84,
                    "nuclear": 5896.77,
                    "oil": 0.0,
                    "solar": 1.62,
                    "unknown": 1467.0,
                    "wind": 3034.16
                },
                "productionCo2Intensities": {
                    "biomass": 230,
                    "coal": 820,
                    "gas": 490,
                    "geothermal": 38,
                    "hydro": 24,
                    "nuclear": 12,
                    "oil": 650,
                    "solar": 45,
                    "unknown": 236,
                    "wind": 11
                },
                "productionCo2IntensitySources": {
                    "biomass": "IPCC 2014",
                    "coal": "IPCC 2014",
                    "gas": "IPCC 2014",
                    "geothermal": "IPCC 2014",
                    "hydro": "IPCC 2014",
                    "nuclear": "IPCC 2014",
                    "oil": "UK POST 2014",
                    "solar": "IPCC 2014",
                    "unknown": "assumes 86.72% biomass, 7.17% solar, 4.58% gas, 0.96% oil, 0.56% peat, 0.01% coal",
                    "wind": "IPCC 2014"
                },
                "renewableRatio": 0.0329,
                "renewableRatioProduction": 0.6828,
                "source": "\"electricityMap Estimation\",\"electricityMap Estimation\",\"svk.se\",\"svk.se\"",
                "stateDatetime": "2021-01-01T00:00:00Z",
                "storage": {
                    "battery": null,
                    "hydro": null
                },
                "totalCo2Discharge": 0,
                "totalCo2Export": 0,
                "totalCo2Import": 0,
                "totalCo2NetExchange": 0,
                "totalCo2Production": 654642460.0,
                "totalCo2Storage": 0,
                "totalConsumption": 18761.33,
                "totalDischarge": null,
                "totalExport": 3950.21,
                "totalImport": 800.51,
                "totalProduction": 18901.75,
                "totalStorage": null
            }
        ]
    }
}
```

**Comment by FelixDQ** [comment] 2022-11-04 08:50
Thanks for reporting @VIKTORVAV99!

Looks like we have 2 issues here.

1. We are showing incomplete data. We currently only have December of 2021 computed, but we still show the yearly average. @Kongkille @madsnedergaard can you add a check, so that we only show data where `above_completeness_threshold` is true?
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/12124251/199931001-a0749939-b785-4d5c-be8f-b5fdf4da8b78.png">

2. It looks like we somehow consider missing data as 0 for these aggregates. I'll investigate this further.

**Comment by VIKTORVAV99** [comment] 2022-11-04 08:55
Could we perhaps introduce a sanity check that checks any zone value is not lower than the lowest CO2 intensity (5.1 with the new regional numbers otherwise 11) and that it's not higher than the highest possible as well?

**Comment by VIKTORVAV99** [comment] 2022-11-04 09:37
@FelixDQ this might also be related, it looks like all data that was previously fetched from SVK for the SE zone is gone? I know there was some inaccuracies with said data but it should only have affected the unknown data.

**Comment by FelixDQ** [comment] 2022-11-04 09:48
Yes, good point. Looks like we are missing data from SE-SE1. I'll investigate.

**Comment by madsnedergaard** [comment] 2022-11-07 10:27
Thanks for catching this and the suggested approaches - we'll add the check for `above_completeness_threshold` to app-backend and make sure the map still renders as intended :)

**Comment by VIKTORVAV99** [comment] 2022-11-10 20:28
Looks like this affects more than just Sweden:
![image](https://user-images.githubusercontent.com/30777521/201198619-51a67137-5026-4871-a1df-384a9aa1c9ea.png)
State file:
```json
{
    "data": {
        "hasData": true,
        "stateAggregation": "yearly",
        "zoneStates": [
            {
                "isValid": false,
                "stateDatetime": "2017-01-01T00:00:00Z"
            },
            {
                "_isFinestGranularity": true,
                "co2intensity": 9.46,
                "co2intensityProduction": 490.0,
                "countryCode": "US-FLA-HST",
                "dischargeCo2Intensities": {
                    "battery": 407.34,
                    "hydro": 407.34
                },
                "dischargeCo2IntensitySources": {
                    "battery": "2018 annual mean carbon intensity by electricityMap",
                    "hydro": "2018 annual mean carbon intensity by electricityMap"
                },
                "exchange": {},
                "fossilFuelRatio": 0.0182,
                "fossilFuelRatioProduction": 1.0,
                "isValid": true,
                "maxDischarge": 0,
                "maxExport": 0,
                "maxImport": 0,
                "maxProduction": 0.02,
                "maxStorage": 0,
                "maxStorageCapacity": 0,
                "price": {
                    "currency": null,
                    "value": null
                },
                "production": {
                    "biomass": 0.0,
                    "coal": 0.0,
                    "gas": 0.02,
                    "geothermal": 0.0,
                    "hydro": 0.0,
                    "nuclear": 0.0,
                    "oil": 0.0,
                    "solar": 0.0,
                    "unknown": 0.0,
                    "wind": 0.0
                },
                "productionCo2Intensities": {
                    "biomass": 230,
                    "coal": 820,
                    "gas": 490,
                    "geothermal": 38,
                    "hydro": 24,
                    "nuclear": 12,
                    "oil": 650,
                    "solar": 45,
                    "unknown": 700,
                    "wind": 11
                },
                "productionCo2IntensitySources": {
                    "biomass": "IPCC 2014",
                    "coal": "IPCC 2014",
                    "gas": "IPCC 2014",
                    "geothermal": "IPCC 2014",
                    "hydro": "IPCC 2014",
                    "nuclear": "IPCC 2014",
                    "oil": "UK POST 2014",
                    "solar": "IPCC 2014",
                    "unknown": "assumes thermal (coal, gas, oil or biomass)",
                    "wind": "IPCC 2014"
                },
                "renewableRatio": 0.0004,
                "renewableRatioProduction": 0.0,
                "source": "\"eia.gov\"",
                "stateDatetime": "2018-01-01T00:00:00Z",
                "storage": {
                    "battery": null,
                    "hydro": null
                },
                "totalCo2Discharge": 0,
                "totalCo2Export": 0,
                "totalCo2Import": 0,
                "totalCo2NetExchange": 0,
                "totalCo2Production": 9800.0,
                "totalCo2Storage": 0,
                "totalConsumption": 67.08,
                "totalDischarge": null,
                "totalExport": 0.0,
                "totalImport": 69.39,
                "totalProduction": 0.02,
                "totalStorage": null
            },
            {
                "_isFinestGranularity": true,
                "co2intensity": 9.03,
                "co2intensityProduction": 490.0,
                "countryCode": "US-FLA-HST",
                "dischargeCo2Intensities": {
                    "battery": 391.46,
                    "hydro": 391.46
                },
                "dischargeCo2IntensitySources": {
                    "battery": "2019 annual mean carbon intensity by electricityMap",
                    "hydro": "2019 annual mean carbon intensity by electricityMap"
                },
                "exchange": {},
                "fossilFuelRatio": 0.0171,
                "fossilFuelRatioProduction": 1.0,
                "isValid": true,
                "maxDischarge": 0,
                "maxExport": 0,
                "maxImport": 0,
                "maxProduction": 0.04,
                "maxStorage": 0,
                "maxStorageCapacity": 0,
                "price": {
                    "currency": null,
                    "value": null
                },
                "production": {
                    "biomass": 0.0,
                    "coal": 0.0,
                    "gas": 0.04,
                    "geothermal": 0.0,
                    "hydro": 0.0,
                    "nuclear": 0.0,
                    "oil": 0.0,
                    "solar": 0.0,
                    "unknown": 0.0,
                    "wind": 0.0
                },
                "productionCo2Intensities": {
                    "biomass": 230,
                    "coal": 820,
                    "gas": 490,
                    "geothermal": 38,
                    "hydro": 24,
                    "nuclear": 12,
                    "oil": 650,
                    "solar": 45,
                    "unknown": 700,
                    "wind": 11
                },
                "productionCo2IntensitySources": {
                    "biomass": "IPCC 2014",
                    "coal": "IPCC 2014",
                    "gas": "IPCC 2014",
                    "geothermal": "IPCC 2014",
                    "hydro": "IPCC 2014",
                    "nuclear": "IPCC 2014",
                    "oil": "UK POST 2014",
                    "solar": "IPCC 2014",
                    "unknown": "assumes thermal (coal, gas, oil or biomass)",
                    "wind": "IPCC 2014"
                },
                "renewableRatio": 0.0007000000000000001,
                "renewableRatioProduction": 0.0,
                "source": "\"eia.gov\"",
                "stateDatetime": "2019-01-01T00:00:00Z",
                "storage": {
                    "battery": null,
                    "hydro": null
                },
                "totalCo2Discharge": 0,
                "totalCo2Export": 0,
                "totalCo2Import": 0,
                "totalCo2NetExchange": 0,
                "totalCo2Production": 19600.0,
                "totalCo2Storage": 0,
                "totalConsumption": 66.64,
                "totalDischarge": null,
                "totalExport": 0.0,
                "totalImport": 66.96,
                "totalProduction": 0.04,
                "totalStorage": null
            },
            {
                "_isFinestGranularity": true,
                "co2intensity": 11.04,
                "co2intensityProduction": 490.0,
                "countryCode": "US-FLA-HST",
                "dischargeCo2Intensities": {
                    "battery": 375.63,
                    "hydro": 375.63
                },
                "dischargeCo2IntensitySources": {
                    "battery": "2020 annual mean carbon intensity by electricityMap",
                    "hydro": "2020 annual mean carbon intensity by electricityMap"
                },
                "exchange": {},
                "fossilFuelRatio": 0.021,
                "fossilFuelRatioProduction": 1.0,
                "isValid": true,
                "maxDischarge": 0,
                "maxExport": 0,
                "maxImport": 0,
                "maxProduction": 0.08,
                "maxStorage": 0,
                "maxStorageCapacity": 0,
                "price": {
                    "currency": null,
                    "value": null
                },
                "production": {
                    "biomass": 0.0,
                    "coal": 0.0,
                    "gas": 0.08,
                    "geothermal": 0.0,
                    "hydro": 0.0,
                    "nuclear": 0.0,
                    "oil": 0.0,
                    "solar": 0.0,
                    "unknown": 0.0,
                    "wind": 0.0
                },
                "productionCo2Intensities": {
                    "biomass": 230,
                    "coal": 820,
                    "gas": 490,
                    "geothermal": 38,
                    "hydro": 24,
                    "nuclear": 12,
                    "oil": 650,
                    "solar": 45,
                    "unknown": 700,
                    "wind": 11
                },
                "productionCo2IntensitySources": {
                    "biomass": "IPCC 2014",
                    "coal": "IPCC 2014",
                    "gas": "IPCC 2014",
                    "geothermal": "IPCC 2014",
                    "hydro": "IPCC 2014",
                    "nuclear": "IPCC 2014",
                    "oil": "UK POST 2014",
                    "solar": "IPCC 2014",
                    "unknown": "assumes thermal (coal, gas, oil or biomass)",
                    "wind": "IPCC 2014"
                },
                "renewableRatio": 0.0015,
                "renewableRatioProduction": 0.0,
                "source": "\"eia.gov\"",
                "stateDatetime": "2020-01-01T00:00:00Z",
                "storage": {
                    "battery": null,
                    "hydro": null
                },
                "totalCo2Discharge": 0,
                "totalCo2Export": 0,
                "totalCo2Import": 0,
                "totalCo2NetExchange": 0,
                "totalCo2Production": 39200.0,
                "totalCo2Storage": 0,
                "totalConsumption": 68.05,
                "totalDischarge": null,
                "totalExport": 0.12,
                "totalImport": 68.12,
                "totalProduction": 0.08,
                "totalStorage": null
            },
            {
                "_isFinestGranularity": true,
                "co2intensity": 6.27,
                "co2intensityProduction": 490.0,
                "countryCode": "US-FLA-HST",
                "dischargeCo2Intensities": {
                    "battery": 391.33,
                    "hydro": 391.33
                },
                "dischargeCo2IntensitySources": {
                    "battery": "2021 annual mean carbon intensity by electricityMap",
                    "hydro": "2021 annual mean carbon intensity by electricityMap"
                },
                "exchange": {},
                "fossilFuelRatio": 0.0116,
                "fossilFuelRatioProduction": 1.0,
                "isValid": true,
                "maxDischarge": 0,
                "maxExport": 0,
                "maxImport": 0,
                "maxProduction": 0.02,
                "maxStorage": 0,
                "maxStorageCapacity": 0,
                "price": {
                    "currency": null,
                    "value": null
                },
                "production": {
                    "biomass": 0.0,
                    "coal": 0.0,
                    "gas": 0.02,
                    "geothermal": 0.0,
                    "hydro": 0.0,
                    "nuclear": 0.0,
                    "oil": 0.0,
                    "solar": 0.0,
                    "unknown": 0.0,
                    "wind": 0.0
                },
                "productionCo2Intensities": {
                    "biomass": 230,
                    "coal": 820,
                    "gas": 490,
                    "geothermal": 38,
                    "hydro": 24,
                    "nuclear": 12,
                    "oil": 650,
                    "solar": 45,
                    "unknown": 700,
                    "wind": 11
                },
                "productionCo2IntensitySources": {
                    "biomass": "IPCC 2014",
                    "coal": "IPCC 2014",
                    "gas": "IPCC 2014",
                    "geothermal": "IPCC 2014",
                    "hydro": "IPCC 2014",
                    "nuclear": "IPCC 2014",
                    "oil": "UK POST 2014",
                    "solar": "IPCC 2014",
                    "unknown": "assumes thermal (coal, gas, oil or biomass)",
                    "wind": "IPCC 2014"
                },
                "renewableRatio": 0.0014000000000000002,
                "renewableRatioProduction": 0.0,
                "source": "\"eia.gov\"",
                "stateDatetime": "2021-01-01T00:00:00Z",
                "storage": {
                    "battery": null,
                    "hydro": null
                },
                "totalCo2Discharge": 0,
                "totalCo2Export": 0,
                "totalCo2Import": 0,
                "totalCo2NetExchange": 0,
                "totalCo2Production": 9800.0,
                "totalCo2Storage": 0,
                "totalConsumption": 67.17,
                "totalDischarge": null,
                "totalExport": 0.0,
                "totalImport": 68.03,
                "totalProduction": 0.02,
                "totalStorage": null
            }
        ]
    }
}
```
I thought the `isValid` key/flag would prevent this or does it just check that the structure/object is valid?

**Comment by Kongkille** [comment] 2022-11-10 20:45
The isValid just does not take into account the threshold. I'll push a fix soon which hopefully resolves this issue!

**Comment by FelixDQ** [comment] 2022-11-14 08:58
I've identified the backend issue. We have rows where the `total_consumption_avg` is computed, but the `carbon_intensity_avg` is not due to missing data. In this case, we should exclude those rows from the average computation.
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/12124251/201617248-bc384a42-c4ed-46d5-befb-c57176f15761.png">

We are a bit focused on another project right now, but I'll try to see if I can fix it quickly.

**Comment by VIKTORVAV99** [comment] 2023-01-06 17:24
@FelixDQ would you consider this issue resolved or should we keep this open?

**Comment by FelixDQ** [comment] 2023-01-06 17:26
I'm currently reprocessing the aggregates with a potential fix for the underlying issue. I'll close this issue when I have validated the fix

**Comment by FelixDQ** [comment] 2023-02-01 13:30
It seems like the fix worked :-) It might take a day or two before the map gets updated

**Closed by FelixDQ** 2023-02-01 13:30 UTC
Labels: bug 🐞, estimated data, data
