### ISSUE TITLE
Potential issues with solar and wind layers on Android devices

### ISSUE THREAD

**Issue by madsnedergaard** [electricitymaps/electricitymaps-contrib#6327] opened 2024-01-08 14:50 UTC
**Describe the bug**
We are getting reports that the solar and wind layers does not work on certain Android devices.

**To be understood**
- Is this happening on the web and/or native app?
- Are all Android devices affected?
- If not, what are the common denominators - is it hardware or software?

**Reported devices**

- Samsung Galaxy A71 - Android 13, Native app, V1.89.0
- Pixel 5, ???

If anyone can reproduce this on their own device, we'd appreciate more details! 🙏

**Comment by jgaye** [comment] 2024-01-22 18:45
Hello,
I can reproduce a blacking of the screen when activating the solar layer on my OnePLus 8 Pro Android 13. Here is a recording of the issue occuring.
https://github.com/electricitymaps/electricitymaps-contrib/assets/4049458/c5bf5f5e-7b4d-41b7-84cc-fce0b49a44ac

Attached is the specs of my Android device: 
![signal-2024-01-22-134344](https://github.com/electricitymaps/electricitymaps-contrib/assets/4049458/4ffb3be8-0005-403c-9363-3e54766d71de)

Let me know if you need more information.

**Comment by jgaye** [comment] 2024-01-31 17:39
I was trying to run the Android app on my machine with Visual Studio to see if I can reproduce this issue on specific Android virtual devices, and debug it. It could use help to successfully run the app though :sweat_smile: .

I got as far as being able to run the mockserver and the web app successfully on my machine.
Then, following the readme I'm able to prepare and run the app on a virtual device, but after startup I get a white screen. I have different errors depending on the android API version I'm using so it's hard to identify the real blocker here.

As a starting point, on API 29 (Q) I get this error (paraphrasing): `unexpected symbol ? on line 1 for asset index-3e4eb939.js`. I did check that file and the js in there looks correct. So it might be an issue when the assets are exported from the web to the android folder.

FYI I'm on an Ubuntu 22.04 machine, and the readme seems to indicate that most contributors use mac, so that might be part of the reason.

If someone can help me run this, I think I can identify the issue and make an MR. Can you help me with that @madsnedergaard ?

**Comment by madsnedergaard** [comment] 2024-11-20 13:51
@VIKTORVAV99, this should be fixed on Android now, right? :)

**Comment by VIKTORVAV99** [comment] 2024-11-20 13:52
> @VIKTORVAV99, this should be fixed on Android now, right? :)

I think so but there is so many Android versions and flavors lurking out there...

But let's close the issue.

**Closed by VIKTORVAV99** 2024-11-20 13:52 UTC
Labels: bug 🐞, help wanted, frontend 🎨
