### ISSUE TITLE
Wrong estimation model datas for nuclear in Germany on new year's day 2023

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#4918] opened 2023-01-01 17:51 UTC
Wrong estimation model datas for nuclear in Germany on new year's day 2023.

Here, at 16:00 there is 6.78GW over 4.06GW installed capacity, and therefor a fake 167.22% load. 

![nuke-em-010123](https://user-images.githubusercontent.com/364418/210180172-dab7edb8-130a-4c89-bde7-d21010197a55.png)

**Comment by VIKTORVAV99** [comment] 2023-01-01 19:12
Thanks for opening a issue about this. Hopefully we can retrain the models to fix this until we have a more permanent solution in place.

**Comment by pierresegonne** [comment] 2023-01-04 13:57
The estimated data has been overwritten by measured data that stays within the capacty bounds. 

Due to reproducibility issues, I'll therefore close this issue.

Note though that we are gathering issues to improve our estimation models so it's super valuable to report these kinds of issues.

**Closed by pierresegonne** 2023-01-04 13:57 UTC
Labels: estimated data
