### ISSUE TITLE
Bug on the country name on hover

### ISSUE THREAD

**Issue by mariehelene** [electricitymaps/electricitymaps-contrib#4652] opened 2022-10-07 19:08 UTC
Bonjour !
Le nom du pays ne se rafraîchit pas sur ma machine (les données, si) lorsque je me déplace d'un pays à un autre (s'ils se touchent).
Ma config :
Ubuntu 22.04.1 LTS
sous Chrome Version 105.0.5195.125 (Build officiel) (64 bits) 

--- Edit, added translation:

> Good morning !
> The country name does not refresh on my machine (the data, if) when I move from one country to another (if they are touching).

**Comment by VIKTORVAV99** [comment] 2022-10-07 20:47
Hi!
If I understood you correctly the problem is that the country names don't update properly?
It would be great if you could add some additional details such as which zones are affected and if it affects all languages? Preferably in English if possible.

**Comment by mariehelene** [comment] 2022-10-08 13:26
Yes, you correctly understood.
It happens for all countries in French.

**Comment by madsnedergaard** [comment] 2022-10-14 07:39
Can you provide a screen recording of this? I cannot reproduce the problem :)

**Comment by VIKTORVAV99** [comment] 2023-06-15 05:37
Closing this as there has been no additional info from the original creator of this issue and we can't replicate it.

**Closed by VIKTORVAV99** 2023-06-15 05:37 UTC
Labels: bug 🐞, frontend 🎨, change requested
