### ISSUE TITLE
Timeline slider and scale buttons invisible in Firefox

### ISSUE THREAD

**Issue by torokati44** [electricitymaps/electricitymaps-contrib#7194] opened 2024-09-11 13:16 UTC
**Describe the bug**

The usual controls to switch between Hourly/Daily/Monthly/Yearly aggregates, and to view historical data, are invisible.
They still work, just can't be seen.

**To Reproduce**
Open the app in Firefox.

**Expected behavior**

All the controls are visible.

**Screenshots**

![image](https://github.com/user-attachments/assets/60f2ca09-f49b-4613-a5e2-629325bb9f02)

**Desktop (if relevant):**
 - OS: Fedora Linux 40
 - Browser: Firefox
 - Version: 130.0

**Additional context**

It started happening just now, when I "updated" to the new version of the app (v1.164.0). It worked fine yesterday (on v1.163.0) - although there was https://github.com/radix-ui/primitives/issues/2777 already.

**Comment by torokati44** [comment] 2024-09-11 13:23
Disabling any of the following properties of the style applied to the
```css
*,
:before,
:after
```
selector:
```css
  --tw-blur: ;
  --tw-brightness: ;
  --tw-contrast: ;
  --tw-grayscale: ;
  --tw-hue-rotate: ;
  --tw-invert: ;
  --tw-saturate: ;
  --tw-sepia: ;
  --tw-drop-shadow: ;
  ```
... in the Developer Tools makes the controls appear as normal.

**Comment by VIKTORVAV99** [comment] 2024-09-11 14:02
Thanks for reporting it!

That sure is odd! 👀

I'll work on a fix right away.

**Comment by torokati44** [comment] 2024-09-11 14:05
On Firefox Android, it works in portrait mode (when the controls are in the pull-up drawer), but not in landscape mode, when they are in the floating panel:
![Screenshot_20240911-160357](https://github.com/user-attachments/assets/83344769-7507-458c-89ef-72b711168cd5)
![Screenshot_20240911-160405](https://github.com/user-attachments/assets/f28819f7-40df-47ed-bda0-9a7d0e030a5d)

**Comment by VIKTORVAV99** [comment] 2024-09-11 14:26
This is the offending PR: https://github.com/electricitymaps/electricitymaps-contrib/pull/7118

The problem is that I don't see anything obvious that would cause this. But it does seem to be related to the tailwind styles.

**Comment by VIKTORVAV99** [comment] 2024-09-11 14:31
According to https://caniuse.com/css-backdrop-filter it should be supported but something is not working as expected.

**Comment by VIKTORVAV99** [comment] 2024-09-11 15:16
@torokati44 could you confirm it's fixed in this version: https://625c35f4.electricitymaps-staging.pages.dev/map

**Comment by VIKTORVAV99** [comment] 2024-09-11 15:20
Thanks!

I'll merge that then and push a new release right away!

**Closed** 2024-09-11 15:20 UTC
Labels: bug 🐞, frontend 🎨

**Comment by VIKTORVAV99** [comment] 2024-09-11 15:30
The fix is deployed but it might take a few hours until it's detected by the current version of the app.

Once again, thanks for reporting it!

**Comment by torokati44** [comment] 2024-09-11 15:31
Thank _you_ for the super quick fix! :partying_face:
