### ISSUE TITLE
Emissions Chart's axis, tooltip and bar heights do not match

### ISSUE THREAD

**Issue by MinerMax555** [electricitymaps/electricitymaps-contrib#5759] opened 2023-08-20 20:36 UTC
**Describe the bug**
It is not clear to me as a user what the emissions chart actually displays. The tooltip gives me tons of CO2Eq per minute, but the y-axis is showing me very small numbers, which are seemingly unrelated (it's not just off by a decimal factor). Additionally, in the example given below the tooltip value decreases between 2021 and 2022 but the bar height increases slightly.

**To Reproduce**
1. Set to Production View
2. Select Poland
3. Select Data from the past 6 years
4. Numbers shown in the tooltip do not match neither y-axis nor visual height of the bars

**Expected behavior**
I'd expect the chart's tooltip y-axis labels and bar height to match

**Screenshots**
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/12732580/424770cc-794b-4748-bbb0-c12c2e8c3c7e)
![image](https://github.com/electricitymaps/electricitymaps-contrib/assets/12732580/c8adda23-059d-4006-8319-f670ef1a5d7a)

**Desktop (if relevant):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 116.0.3

**Additional context**

**Comment by tonypls** [comment] 2023-08-21 07:28
Thanks for the reminder, I believe this is a duplicate of #5140

**Closed** 2023-08-25 11:43 UTC
Labels: bug 🐞, frontend 🎨
