### ISSUE TITLE
Display Exchange Tooltip on Mobile

### ISSUE THREAD

**Issue by tonypls** [electricitymaps/electricitymaps-contrib#5030] opened 2023-02-06 10:32 UTC
**Describe the bug**
We want to display the exchange tooltip on mobile devices, currently there is not handler for tapping on exchanges, the exchange tooltip is only shown on hover. 

The exchange tooltip is useful information and we should enable users to view it on mobile

**To Reproduce**
Open the app on a mobile device, tap an exchange arrow

**Expected behavior**
As a mobile user when tapping an exchange arrow the exchange tooltip is displayed

**Smartphone (if relevant):**
All mobile devices, web app and mobile app

**Comment by madsnedergaard** [comment] 2023-02-06 15:00
Duplicate of #5030, but let's keep this one as it has additional context :)

**Comment by tonypls** [comment] 2023-02-06 15:50
> Duplicate of #5030, but let's keep this one as it has additional context :)

Is this not the #5030 itself? 🤯

**Closed** 2023-02-14 11:56 UTC
Labels: bug 🐞, frontend 🎨, good first issue
