### ISSUE TITLE
Realtime Data funktionieren nicht

### ISSUE THREAD

**Issue by 104790562** [electricitymaps/electricitymaps-contrib#4116] opened 2022-05-11 09:45 UTC
Hallo,

die interaktiven Karten sind nicht mehr mit den aktuellen Daten hinterlegt.

Mfg
Robert

**Comment by VIKTORVAV99** [comment] 2022-05-11 12:20
Hello and welcome to GitHub @104790562! 🎉

If I understood you correctly you are trying to say the map no longer have realtime data?

It would be great if you could provide a little more detail in English so we can determine what the issue is.

**Comment by jarek** [comment] 2022-05-11 14:14
Hallo Robert,

Bei mir funktionert es gerade: https://app.electricitymap.org/zone/DE 
Geht es bei Dir? Falls nicht, ein Screenshot wäre hilfreich

---

It's working for me, for example: https://app.electricitymap.org/zone/DE
Is it working for you now? If not, a screenshot would be helpful to try to diagnose problems

![de](https://user-images.githubusercontent.com/47415/167870606-1e674814-6a10-45df-9928-7052d0ace26a.png)

**Comment by VIKTORVAV99** [comment] 2022-12-01 21:43
Closing this as we didn't receive any additional information.

**Closed by VIKTORVAV99** 2022-12-01 21:43 UTC
