### ISSUE TITLE
[Bug]: Index issue with yearly historical view

### ISSUE THREAD

**Issue by ChrisRie89** [electricitymaps/electricitymaps-contrib#5339] opened 2023-04-28 22:53 UTC
### When did this happen?

2023-04-28

### What zones are affected?

Germany

### What is the problem?

According to electricitymaps, German gCO₂eq/kWh did rise from 397 in 2019 to 447 in 2020. Mostly due to higher coal consumption. 

According to official data: https://www.destatis.de/EN/Press/2021/03/PE21_101_43312.html

Electricity from coal declined in 2020 compared to 2019 and was overtaken for the first time by windenergy.

What's the cause of the difference between both data sets?

**Comment by VIKTORVAV99** [comment] 2023-04-28 23:16
I think you got the years confused, the Electricity Maps data shows 441 gCO2eq/kWh in 2019 and 397 gCO2eq/kWh for 2020.

You can also clearly see that wind overtook coal production as your source pointed out.

**Comment by ChrisRie89** [comment] 2023-04-28 23:25
not sure about this, take a look at the attachments.
<img width="429" alt="Bildschirmfoto 2023-04-28 um 19 24 03" src="https://user-images.githubusercontent.com/132109323/235269150-a5d8c544-10e0-485a-a1a2-e0e847845f84.png">
<img width="437" alt="Bildschirmfoto 2023-04-28 um 19 23 57" src="https://user-images.githubusercontent.com/132109323/235269151-bc1d6374-ff7d-4d7e-97ad-d4f9f6ab5c6e.png">

**Comment by VIKTORVAV99** [comment] 2023-04-29 09:30
Are you using the app? If so please make sure it's updated.

It should look like this:
![image](https://user-images.githubusercontent.com/30777521/235295606-6c4fb7bb-29b9-4b3b-a6f9-c3e2f7d6f7e9.png)

Notice that the time slider at the bottom starts at 2018 and ends at 2022, not 2017 and 2021 respectively.

**Comment by ChrisRie89** [comment] 2023-04-29 15:15
Hm, that’s strange. I was using the webapp. Just downloaded the iPhone app but it shows the same (wrong) data like the webapp.
Any idea how to solve this? Thanks!

**Comment by VIKTORVAV99** [comment] 2023-04-29 16:22
> Hm, that’s strange. I was using the webapp. Just downloaded the iPhone app but it shows the same (wrong) data like the webapp. Any idea how to solve this? Thanks!

Could you provide some more info like the iOS version then we try and debug things locally.

I have another idea of a fix though but it will take some time to implement and test said idea.

**Comment by jarek** [comment] 2023-05-02 02:28
Using web app https://app.electricitymaps.com/zone/DE and hard-reloaded to avoid caches. Firefox 112.0.1 / Ubuntu

Getting 397 g for aggregated 2019 for Germany, and 447 g for aggregated 2020, and 480 g for aggregated 2021. These are all for consumption.

[2019 screenshot](https://user-images.githubusercontent.com/47415/235566442-a7363f50-2ac7-4013-b6d0-40392c8e7222.png) (disregard the red line, it's a misbehaving mouse gestures plugin)

[2020](https://user-images.githubusercontent.com/47415/235566460-62dd2de0-9076-476e-b8e3-e320ad4997ce.png)

[2021](https://user-images.githubusercontent.com/47415/235566490-aa0335fc-c303-4ce6-bf20-1fb36591ee7f.png)

**Comment by VIKTORVAV99** [comment] 2023-05-02 07:06
> I'm seeing that in my screenshot, the last 5 years are 2017 through 2021, while in @VIKTORVAV99's it's 2018 through 2022. Do you have newer data on an internal system?

I always use production data and the public endpoint for testing (app.electricitymaps.com) so this should be what you are seeing as well. I did use Edge Version 112.0.1722.64 but beyond that there should be no difference.

So it does look like it is an Index issue in the frontend so I'll update the issue title and tags.

**Comment by sporadicus** [comment] 2023-05-31 19:23
I believe this issue arises from the fact that dates/times in the TimeAxis component are shown in the user's local timezone. (Apologies in advance for the length of this comment.)

By default, of course, the TimeController component shows hourly data for the most recent 25 hours. The slider that allows the user to choose which hour's data to show has 25 tick marks, each representing one of the last 25 hours (e.g. "1:00PM").

These tick marks are derived from the 25 ```dateTime``` values that are returned by the HTTP state query, each of which aligns with the top of an hour (e.g. "2022-12-04T08:00:00Z"). To determine the hourly tick mark values, a Date object is created from each of these ```dateTime``` values, and then the hour value of each Date object is isolated by calling the ```format()``` method of a newly instantiated Intl.DateTimeFormat object. Importantly, this Intl.DateTimeFormat object instantiation uses the user's local timezone by default, so the tick marks represent points in time expressed in terms of the user's local timezone.

Now moving to the other end of the TimeAxis picker (the "yearly" option), we receive 5 ```dateTime``` values from the HTTP state query, and each aligns with 12:00am (UTC) of January 1 of its respective year (e.g. "2017-01-01T00:00:00Z"). The values of the slider's 5 tick marks are derived in much the same way as the hourly tick marks were: a Date object is created from each returned ```dateTime``` value, and this time the year value of each Date object is isolated by calling ```format()``` on a newly instantiated Intl.DateTimeFormat object. And, as before, the Intl.DateTimeFormat object uses the user's local timezone by default, but this time there's a problem.

If the user is in the UTC timezone, or a timezone whose UTC offset is positive (e.g. Copenhagen's UTC+01:00 or +02:00), then the resulting isolated year values will appear correctly. But if the user's timezone has a negative UTC offset, then each isolated year value will be one year too early. To illustrate, if the returned ```dateTime``` value is "2018-01-01T00:00:00Z" and the user is in New York (in the winter), the Intl.DateTimeFormat object that is instantiated will represent that time as something like "Sun Dec 31 2017 19:00:00 GMT-0500 (Eastern Standard Time)" *before* isolating the year, resulting in a tick mark value of ```2017``` instead of the desired ```2018```.

How to proceed? It feels to me like the current behavior of the ```hourly``` setting (namely, show tick mark values in the user's timezone) aligns correctly with what a user would want and expect, but that the same behavior gives counterintuitive results with the other three settings (```daily, monthly, and yearly```). So, for what it's worth, my intuition would be to show UTC-based tick mark values for these latter three settings. I'm sure there are many possible ways to accomplish this outcome; the one that seems simplest to me is to modify ```formatDateTick()``` in the file ```formatting.ts``` such that the instantiation of Intl.DateTimeFormat utilizes UTC instead of the user's local timezone when the TimeAxis setting is not ```hourly```. 

I can create a PR that implements the above code modification if that's something desired. I've tested this solution in a local Vite-based implementation, but I don't have enough familiarity with the codebase to feel comfortable presuming that this proposed solution is the most preferable one.

(Incidentally, there are two places in the user interface where the currently selected slider value is represented; one in the TimeDisplay component and the other in the page header. These suffer from a similar issue (i.e. off by one year in UTC negative offset timezones), which can be corrected in an analogous manner by modifying the ```formatDate()``` function in ```formatting.ts```.)

**Comment by jarek** [comment] 2023-06-01 02:14
Very well spotted. I can confirm my UTC offset is indeed negative: North American EST/EDT, UTC-4 at the moment

**Comment by VIKTORVAV99** [comment] 2023-06-01 10:14
Thanks for the long and thorough comment!

Looks like this might indeed be the source of the issue and the proposed solution sounds like a good starting point at the very least!

If you wish you can go ahead and create a PR for it and I'll help as much as needed. It will be easier to give a review of the implementation when we can see how it directly interacts with the rest of the code but I don't think there is any problems with the proposed solution.

**Closed** 2023-06-05 14:47 UTC
Labels: bug 🐞, frontend 🎨
