### ISSUE TITLE
Add available locales to language selector

### ISSUE THREAD

**Issue by haraldgroven** [electricitymaps/electricitymaps-contrib#6165] opened 2023-11-22 10:30 UTC
The Norwegian locale has now been 100% translated from English. 
**It would be great if _Norwegian (bokmål)_ was added to the language menu in the app.** 

Most users would never know that translation is available by adding `?lang=no-NB` to the url, so translations not available in the language selector are practically invisible. 

Same feature request applies to any other translated locales currently not present among the 6 translations available. 

<img width="301" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/911226/96b770c4-931f-4be4-b8ab-4ececea5277b">

**Comment by VIKTORVAV99** [comment] 2023-11-24 19:16
Thanks for opening the issue but I'm not really sure what the issue is?
It's already in there?
<img width="163" alt="image" src="https://github.com/electricitymaps/electricitymaps-contrib/assets/30777521/86ca9b64-f5e1-4d76-b6ad-ce34810e0423">

**Comment by jarek** [comment] 2023-11-25 03:10
The fact that the language list scrolls is not really obvious. The scrollbar contrast is near zero.

Also duplicate #6072

**Comment by haraldgroven** [comment] 2023-11-25 09:42
After many hours of using the web app, I have never noticed the hidden scrollbar. 
I'm probably not the only user who are unable to guess the existence of it.
Improving the visibility of the UI will be good for both  i18n, UU and usability :-)

**Comment by VIKTORVAV99** [comment] 2023-11-25 10:51
There is a plan to migrate more elements to the semitransparent view you can see on the elements around the language bar and there is also some ideas floating around internally now how we can make the main view less cluttered as well as making the settings clearer.

Unfortunately we have not really had the time to prioritise this yet but we are looking into it.

But once again we are looking into the visual profile of the app (not just this) and will be making changes in the near future.

However since this is a duplicate of #6072 as Jarek mentions I will be closing it in favour of that one.

**Closed by VIKTORVAV99** 2023-11-25 10:51 UTC
Labels: frontend 🎨
