### ISSUE TITLE
[Data Issue]: Discrepancy w grid ISO for GB

### ISSUE THREAD

**Issue by corradio** [electricitymaps/electricitymaps-contrib#4835] opened 2022-12-05 07:47 UTC
### When did this happen?

Sunday 4th @ 8:36 PM

### What zones are affected?

GB

### What is the problem?

Our data:
![image](https://user-images.githubusercontent.com/1655848/205581768-3521711e-5a48-4083-8bc3-ad357ec1a19d.png)

Grid ISO:
![image](https://user-images.githubusercontent.com/1655848/205581778-ec301534-ac5c-47de-8fb7-d86301a1a26f.png)

**Comment by corradio** [comment] 2022-12-05 07:54
Could be related to https://github.com/electricitymaps/electricitymaps-contrib/issues/4829

**Comment by unitrium** [comment] 2022-12-05 08:32
The latest parser data we have for GB seems to date from the 30/11.
A quick look on the [ENTSOE website](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=16.11.2022+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=16.11.2022+00:00|CET|DAYTIMERANGE&area.values=CTY|10Y1001A1001A92E!CTY|10Y1001A1001A92E&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) seems like there is an issue for UK as there is no available data at all.

**Comment by unitrium** [comment] 2022-12-06 10:55
The issue is on ELEXON's side.
Most of their power generation api report values of 0.
https://www.bmreports.com/bmrs/?q=actgenration/actualaggregated

**Comment by unitrium** [comment] 2022-12-06 10:56
We are asking them a status update on this.

**Comment by kaz911** [comment] 2022-12-06 11:10
UK is not listed as an ENTSOE member

**Comment by corradio** [comment] 2022-12-06 11:37
@unitrium isn't the issue coming from the estimation model (screenshot shows it's estimated)?

**Comment by unitrium** [comment] 2022-12-06 17:44
Several things are happening:
- we don't get any parser data since the 30/11 for this zone. This is due to the BRMS report to currently report nuclear and gas generation to be 0. We have a validation layer in the ELEXON parser that discards a data point that has nuclear or gas at 0.
#4842 addresses this but it will mean that we will have datapoints for the parser with anything appart from wind generation to be at 0.
- currently GB uses the standard ESTIMATED_TIME_SLICER_AVERAGE, I'm not sure yet why it puts wind to 0.
we could roll out another estimation model.

**Comment by VIKTORVAV99** [comment] 2022-12-06 18:30
@unitrium is there a way to always use the estimated data even when the parser returns (valid) data?

If there is we could perhaps force the use of estimations and use the parser data to continuously train the wind models (and any other data that becomes available) and discard the 0 values for nuclear and gas etc on the backend?

**Comment by unitrium** [comment] 2022-12-07 14:13
At the moment our estimation model is back on track. We have the estimated wind back. The datasource is still down at the moment we have a ticket open with them they should reply within the next 2 business days.

**Comment by pierresegonne** [comment] 2022-12-15 17:24
Any updates from ELEXON @unitrium ?

**Comment by PinkFrosties** [comment] 2022-12-19 10:22
Hi! 
It seems the issue is partly resolved.. Wind data is now non-zero but still showing gaps to real data:
![image](https://user-images.githubusercontent.com/90898861/208403748-3e6afa74-4c23-4b08-bf12-cfdf9372bced.png)
![image](https://user-images.githubusercontent.com/90898861/208403820-5a56a0bc-b03e-41c3-94a0-d74791823df9.png)

**Comment by kaz911** [comment] 2022-12-19 10:27
The data has been static for quite a while compared to iamkate. It is stuck the same place it was this morning at 6am uk time.

The UK data is unusable....

**Comment by unitrium** [comment] 2022-12-19 10:34
The data is currently estimated because we still don't get any new data from ELEXON. We have an open ticket with them, they just said they are aware of the issue for now, no ETA on when this will be fixed on their side.

**Comment by kaz911** [comment] 2022-12-19 11:00
This is a problem that will never be solved if a service is 100% dependent on a single data source/aggregator. 

A service like ElectricityMaps - should have at least 1 backup source for each data source.

Right now it would probably be better to just "erase" the UK data - as it is far from correct - and have not been since around December 3rd (at least)

**Comment by corradio** [comment] 2022-12-19 11:04
Does anyone know what the data source differences between https://grid.iamkate.com/ and ours are? If iamkate works, then I guess we should mimic their implementation?

**Comment by kaz911** [comment] 2022-12-19 11:05
All Iamkate's data sources are listed at the bottom of the page.....

**Comment by kaz911** [comment] 2022-12-19 11:06
> Most data comes from the [Balancing Mechanism Reporting System](https://www.bmreports.com/) and is updated at five minute intervals. Embedded solar and wind data comes from [National Grid ESO](https://data.nationalgrideso.com/) and is updated at half hour intervals. Emissions data comes from the [Carbon Intensity](https://carbonintensity.org.uk/) project by the National Grid and the University Of Oxford Department Of Computer Science, and is updated at half hour intervals.

**Comment by KateRoseMorley** [comment] 2022-12-19 11:20
On https://grid.iamkate.com I use older versions of the BMRS feeds, which seem to be more reliable but will be retired at some point next year.

Five-minute generation data: https://www.bmreports.com/bmrs/?q=ajax/xml_download/FUELINST/xml/
Half-hour generation data: https://www.bmreports.com/bmrs/?q=ajax/xml_download/FUELHH/xml/
Interconnector data: https://www.bmreports.com/bmrs/?q=ajax/xml_download/INTERFUELHH/xml/
Pricing data: https://www.bmreports.com/bmrs/?q=ajax/xml_download/DERSYSDATA/xml/

Note that the generation feed never reports negative values, so can’t be used on its own for interconnectors and storage. I use the five-minute feed for the live figures at the top of the page and half-hour feeds for everything else.

I use the National Grid ESO feed for embedded wind, embedded solar, and pumped storage pumping figures (which combined with the data from BMRS gives the full picture): https://data.nationalgrideso.com/backend/dataset/7a12172a-939c-404c-b581-a6128b74f588/resource/177f6fa4-ae49-4182-81ea-0c6b35f26ca6/download/demanddataupdate.csv

Finally, I use the Carbon Intensity feed for emissions: https://api.carbonintensity.org.uk/intensity/%s/pt24h

**Comment by corradio** [comment] 2022-12-19 11:31
Thank you so much @KateRoseMorley ! Big fan of the page you made by the way ;-)

@unitrium do you think it would be a good idea to ask the community to update our [elexon parser](https://github.com/electricitymaps/electricitymaps-contrib/blob/master/parsers/ELEXON.py) to use the data sources that @KateRoseMorley is also using? This could provide more consistency (and seems to be more robust).

**Comment by unitrium** [comment] 2022-12-19 12:36
It's probably a good to use FUELINST report as long as the B1620 is incomplete. We kind of already integrated part of it in our parser.
I will update the parser this afternoon to use this data source. We just need to update the production source, all other sources seem to work correctly at the moment.

**Comment by unitrium** [comment] 2022-12-21 08:28
We have updated our parser to use FUELINST for the time being, the data is therefore back to being live data. We have run a refetch to replace the inaccurate estimated data.

Two things remain to be done:
- FUELINST report will be decommissioned sometime in 2023, we need to monitor that situation.
- We haven't integrated the pumped storage yet, so this figure is missing at the moment.

**Comment by unitrium** [comment] 2022-12-23 13:40
Opened a PR to add embedded wind and solar as well as hydro storage. Then we will have the full picture.
The change will only be effective after our holiday code freeze around the 2nd of January.
https://github.com/electricitymaps/electricitymaps-contrib/pull/4899

**Closed** 2023-01-02 21:41 UTC
Labels: data, needs triage

**Comment by unitrium** [comment] 2023-01-03 09:57
The last remaning bit was merged yesterday, so we're back on full reporting of the GB data. We will assess when necessary to switch back to BMR reports.
