### ISSUE TITLE
[Data Issue]: Lithuania capacities are outdated

### ISSUE THREAD

**Issue by mathilde-daugy** [electricitymaps/electricitymaps-contrib#5256] opened 2023-04-03 11:59 UTC
### When did this happen?

Apr 2, 2023, 4:00 PM

### What zones are affected?

LT 

### What is the problem?

Wind capacity seems to be outdated as we have total wind production higher than the installed capacity for some hours 
<img width="699" alt="image" src="https://user-images.githubusercontent.com/107848894/229502642-4f11b2a9-b11f-478d-82c0-7c09fd083a00.png">

**Comment by VIKTORVAV99** [comment] 2023-04-03 16:57
> Was fixed in #5250

I suspected as much but didn't have the opportunity to check yet so thanks for confirming!

@mathilde-daugy I'm going to close this as the issue is close and we just need to merge contrib to the mono repo.

**Closed by VIKTORVAV99** 2023-04-03 16:57 UTC
Labels: help wanted, capacity, good first issue, data
