### ISSUE TITLE
Manually update precision of grid zone borders.

### ISSUE THREAD

**Issue by zrsmithson** [electricitymaps/electricitymaps-contrib#5149] opened 2023-03-02 20:40 UTC
## Description
Many of the polygons in [world.geojson](https://raw.githubusercontent.com/electricitymap/electricitymap-contrib/master/web/geo/world.geojson) have data quality issues:
- loosely aligned with ocean boundaries
- holes and overlaps
- polygons do not always follow the right hand rule (CCW for an exterior border) which requires normalization

I found the [contribution guide for these geometries](https://github.com/electricityMaps/electricitymaps-contrib/wiki/Edit-world-geometries#how-are-the-geometries-set-up), but I still had some questions.
- Is there any authoritative source on these grid zone boundaries, or are these ultimately defined here?
- Is there a conscious choice to lower the number of vertices to sacrifice accuracy for performance, or is it just a low priority optimization?
- Do any zones go beyond country borders, or is there an implicit hierarchy in the naming, something like `f"{country_code}-{region_id}-{subregion_id}"`? There are two exceptions to this, North Cyprus ("XX") and Nagorno-Karabakh ("NKR"), so I'm curious if that is by design for disputed regions. I couldn't find any example where zones overlap multiple countries.

## Examples
Although you can also see them in the github rendering of [world.geojson](https://github.com/electricitymaps/electricitymaps-contrib/blob/master/web/geo/world.geojson), the following images were rendered with geojson.io which is more interactive.

Direct link: https://geojson.io/#data=data:text/x-url,https://raw.githubusercontent.com/electricitymap/electricitymap-contrib/master/web/geo/world.geojson

Ocean border coverage: NYC
![Screenshot 2023-03-02 2 38 13 PM](https://user-images.githubusercontent.com/37639247/222544332-4f802a1b-3086-42ef-b5ac-9ca32105c9a8.png)

Holes: Montreal
![Screenshot 2023-03-02 2 38 38 PM](https://user-images.githubusercontent.com/37639247/222544330-06060926-f91b-4591-ae04-4365562656da.png)

Disjointed border: Ontario/Quebec
![disjointed](https://user-images.githubusercontent.com/37639247/222544327-e21ddb8d-b49d-44ea-bb0e-9414a14d8740.png)

**Comment by VIKTORVAV99** [comment] 2023-03-02 21:12
Hi @zrsmithson!
I'll address these concerns one by one so bear with me here:
> loosely aligned with ocean boundaries

This is mostly by design, our world file is already over 1mb and is by a far margin the biggest part of the app. Increasing the accuracy on the ocean borders would increase the bundle size exponentially so this is not really an option. But that does not mean we couldn't adjust the borders to better match the ocean without increasing the number of points (coordinate pairs).

> holes and overlaps

This should not be happening and is likely an error in the underlying data. The only "holes" that should exist are major lakes and in no cases should there be overlaps. Although we do accept some margin of error in the build system but if we can remove these it would be great.

> polygons do not always follow the right hand rule (CCW for an exterior border) which requires normalization

Not really sure what you mean here so please expand on it further.

> Is there any authoritative source on these grid zone boundaries, or are these ultimately defined here?

There is not as these differs from country to country, if we take Sweden for example we tried to match them as close as possible to the ones used by SVK, the swedish TSO, on https://www.svk.se/kontrollrummet. But these can be bidding zone borders, regional borders, state border or as in most cases country borders.

> Is there a conscious choice to lower the number of vertices to sacrifice accuracy for performance, or is it just a low priority optimization?

We don't use triangle polygons but rather convert the GeoJson to TopoJson which saves and convert borders between polygons to "line" segments that can then be reused by each individual feature so vertices are not a issue but the number of points on the border are. These are purposefully sacrificed to keep performance up and size down. In fact we even round points to 4 decimal accuracy as well and have been thinking about reducing this to 3.

> Do any zones go beyond country borders, or is there an implicit hierarchy in the naming, something like f"{country_code}-{region_id}-{subregion_id}"? There are two exceptions to this, North Cyprus ("XX") and Nagorno-Karabakh ("NKR"), so I'm curious if that is by design for disputed regions. I couldn't find any example where zones overlap multiple countries.

As of right now there is only two levels of hierarchy which comprise of the country key and the subdivision key. If there is a subdivision key assigned by the TSO or another authorative domain we use that otherwise we create one that makes logical sense from the region or state border, or in the case of the US which power company that runs them. However these are not implicit and must be explicitly set. As for the "size" or span of the zone that is usually defined by the what the data we get form that zone represent. For example the Cyprus data returned does not include the power generated on North Cyprus which created the need to split the two to get a accurate representation of the data we have. So this is not for any political stance on our part.

I'll have to look into NKR though as it don't look like we have any data for Azebajan that would have required this (but we do have some for Armenia) but I'll look deeper into this when I have the time.

**Comment by jarek** [comment] 2023-03-03 03:59
I don't see a particular problem in the Montréal example? It's the result of rounding/simplification to get the filesize smaller. Montréal is an island so it doesn't seem a big problem to have it rendered as... an island. We have other freshwater islands also rendered as island: Manitoulin in Ontario, Reindeer Island in Manitoba, Olkhon in Siberia, several islands in Great Slave Lake in Northwest Territories.

**Comment by jarek** [comment] 2023-03-03 13:22
... although this apparently new lake on the border between Québec and Maine is a little concerning! I don't recall that on a world map.
![image](https://user-images.githubusercontent.com/47415/222730004-cca2188f-f347-4561-9cf4-563e22edf7a9.png)

**Comment by madsnedergaard** [comment] 2023-04-04 19:22
Thanks for providing great questions - and also thanks to @VIKTORVAV99 for answering thoroughly :)

I'd just like to add here that **we'd love any help on improving geometries** and making them more accurate (without sacrificing file size)! 

To by knowledge, this will most likely be a manual effort of going through coast lines on geojson.io (or QGIS or similar tools) to move boundaries around. We unfortunately don't have the time and capacity to do this, so we'd love it if anyone else would help out with this. Even just small improvements for specific zones are very be welcome :)

**Comment by VIKTORVAV99** [comment] 2023-07-03 18:48
Just to provide an update on this:
In #5443 I fixed the issue mentioned by Jarek and cleaned up some overlapping borders and small gaps but I wouldn't consider this issue closed as there is many more borders to look over.

Next steps are to look over the US geometries and zones to fix some borders (and possibly remove a zone or two that are no longer in use by the data provider (EIA)).

**Comment by VIKTORVAV99** [comment] 2024-09-12 13:46
This has been addressed by a few different PR since it was opened so I'll consider this closed.

If there are specific geo issues feel free to open new issues for them.

**Closed by VIKTORVAV99** 2024-09-12 13:46 UTC
Labels: help wanted, geometry
