### ISSUE TITLE
[Data Issue]: Erroneous data for Western Australia 22 and 23 December (CET)

### ISSUE THREAD

**Issue by q--** [electricitymaps/electricitymaps-contrib#6287] opened 2023-12-23 15:15 UTC
### When did this happen?

Dec. 22 and 23 (CET)

### What zones are affected?

AU-WA

### What is the problem?

Production modes seem to disappear at some time points:

![Data error for Western Australia - screenshot of part of the zone panel in ElectrictyMaps](https://github.com/electricitymaps/electricitymaps-contrib/assets/2470175/b1b516d2-a0ea-48f4-a91c-66620c3137fb)

**Comment by q--** [comment] 2023-12-23 15:16
By the way, is it a good thing if I make an issue for errors like this that are probably due to the data source, or do your automated systems catch this?

**Comment by VIKTORVAV99** [comment] 2023-12-23 16:17
> By the way, is it useful if I make an issue for errors like this that are probably due to the data source, or do your automated systems catch this?

We do have some automated systems to correct it (but not really flag it yet) that run on a schedule.

We are creating an automated system to flag data though but it has not been deployed yet (hopefully in January though).

So until then these are great and help me keep tabs on them (and manually run our pipelines if needed).

**Comment by VIKTORVAV99** [comment] 2023-12-23 16:28
Looks like the source data is also the cause here, which is unfortunate.

Source: https://opennem.org.au/energy/wem/?range=30d&interval=1d&view=discrete-time

Most of our team are on holidays now but if this persists we will manually flag this data so our estimations can take over instead, not ideal but should be better than the current data.

**Comment by VIKTORVAV99** [comment] 2023-12-23 16:59
Looks like we also lost the ability to backfill data. I have opened a issue for it at https://github.com/opennem/opennem/issues/349, hopefully we will be able to restore this ability as soon as possible and refetch all the affected data once it has been fixed at the source.

**Comment by madsnedergaard** [comment] 2024-11-20 14:28
Closing this again as we can't do much on it right now, but our data quality detection and estimation models have improved greatly since this was created :)

**Closed by madsnedergaard** 2024-11-20 14:28 UTC
Labels: data, external
