### ISSUE TITLE
Update Vite version

### ISSUE THREAD

**Issue by VIKTORVAV99** [electricitymaps/electricitymaps-contrib#5215] opened 2023-03-20 16:38 UTC

**Comment by madsnedergaard** [comment] 2023-03-23 21:09
Duplicate of 5215

**Closed by madsnedergaard** 2023-03-23 21:09 UTC

**Comment by VIKTORVAV99** [comment] 2023-03-23 21:11
> Duplicate of 5215

Emm, this is 5215... 😅

**Comment by madsnedergaard** [comment] 2023-03-27 06:02
> > Duplicate of 5215
> 
> Emm, this is 5215... 😅

🤦  #5213
